"""empty message

Revision ID: 2605a97e0dff
Revises: a14b90aa8e7f
Create Date: 2024-01-30 01:46:40.751842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2605a97e0dff'
down_revision: Union[str, None] = 'a14b90aa8e7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_pc', sa.Column('last_updated_flag', sa.Boolean(), nullable=False, server_default="0"))
    op.execute('ALTER TABLE t_pc MODIFY last_updated_flag BOOL NOT NULL DEFAULT 0 AFTER delete_flag')

    op.add_column('t_ios', sa.Column('last_updated_flag', sa.Boolean(), nullable=False, server_default="0"))
    op.execute('ALTER TABLE t_ios MODIFY last_updated_flag BOOL NOT NULL DEFAULT 0 AFTER delete_flag')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('t_pc', 'last_updated_flag')
    op.drop_column('t_ios', 'last_updated_flag')
    # ### end Alembic commands ###
